name: Load dataset to Elasticsearch
on:
  workflow_dispatch: {}
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run loader
        env:
          ES_URL: ${{ secrets.ES_URL }}
          ES_API_KEY: ${{ secrets.ES_API_KEY }}
          ES_INDEX: ${{ secrets.ES_INDEX }}
        run: python scripts/loader.py
